deployment: master-
  staging:
    branch: master
    heroku:
      appname: foo-bar-123
curl -H "Authorization: bearer token" -X POST -d " \
 { \
   \"query\": \"query { viewer { login }}\" \
 } \
" https://api.github.com/graphql
query {
  repository(owner:"octocat", name:"Hello-World") {
    issues(last:20, states:CLOSED) {
      edges {
        node {
          title
          url
          labels(first:5) {
            edges {
              node {
                name
              }
            }
          }
        }
      }
    }
  }
}
deployment:
  staging:
    branch: master
    codedeploy:
      appname-1234:
        application_root: /
        region: us-east-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: my-bucket
            key_pattern: appname-1234-{BRANCH}-{SHORT_COMMIT}
        deployment_group: my-deployment-group
